### ISSUE TITLE
Dynamic template

### ISSUE THREAD

**Issue by cirotix** [tyomo4ka/django-reactive#4]
Hi @tyomo4ka 

Thank you for your app and work!

Would you be interested by a contribution to have dynamic `schema` and `ui_schema`?

The idea is to provide a choice field to the editor. He would choose one `template` when he creates the model. He then saves it. When he updates, the ReactJSONSchemaField present the form, based on the selected template.

It is somehow similar to https://github.com/The-Politico/django-foreignform

However they are a few things that I don' like in this app:
1. The form in render via the admin class. Therefore you can't have multiple react-jsonschema field per model (not an issue for me) and you can't have inlined model (this is an issue for me).

1. The template (schema + ui_schema) is saved in db, in a dedicated model. IMO this is unnecessary, as if you create a new jsonschema, you will probably need some code for the html template (or whatever you need to do with the data). Furthermore this is dangerous because one with the right permissions can very easily change the schemas in db, and destroy some data. At last, it is not versioned and any change requires a data migration to be deploy. Therefore I think that schema belongs to code rather than to db.

1. I have contributed a PR (update the more recent versions) and have opened an issue to offer to contribute some code to improve the first point (use a widget instead of the admin class to render).  I still have no response so I don't know if they are willing to accept contribution. I am fine with that (it takes to time to review and integrate contributions) but I'd rather not fork a project and contribute to an existing one. 

So I prefer your approach of the problem, but I need to be able to let the editor choose which schema he wants for the field. I would make sure that we have some backward compatibility.

Cheers,
Damien

**Comment by cirotix** [comment]
Hi there,

I had no news on the issue so I guess that my contribution is not of interest to the project (I am fine with that). For the record, I have developed the above-described modifications. Should you want to have a look you can find it here:  https://github.com/briefmnews/django-reactive
Please note that this is not backward compatible with your branch because I didn't it backward compatibility. But should you want to merge my code in your code I would be happy to provide a clean PR with backward compatibility.

**Comment by tyomo4ka** [comment]
Hey @cirotix. Thanks for your feedback. And sorry I didn't have time to look here for ages.

I am planning to do some maintenance for this project – update dependencies, migrate ci to GitHub actions, fix a couple of small bugs, etc. But to be honest I wasn't thinking about implementing something similar to django-foreign-form. I will find some time this weekend to look at your project and let you know what I think. 

In any case thanks for raising this issue glad that someone else found this project interesting. 

Cheers.

**Comment by cirotix** [comment]
Hi @tyomo4ka 
Glad to hear that! Let me know if you need more info from me.
Cheers

**Comment by tyomo4ka** [comment]
Hi @cirotix!

I finally found some time to check your code.

Thanks again for offering a contribution to this library, but to be honest, I don't think it will be the best solution to implement this behavior in Django, as you need to save the form in order to update a part of it which is not very convenient for customers.

In my opinion, if you want behavior like this it is better to use `one of` field which is supported by RJSF. Check this one https://react-jsonschema-form.readthedocs.io/en/latest/dependencies/#dynamic

Of course, both solutions have pros and cons. I like yours because it's easier to understand for Django developers, but usability-wise it looses to the Dynamic fields offered by RJSF.

**Comment by cirotix** [comment]
Hi @tyomo4ka 
Too bad that you are not ok with our patch. I think that the `one of` can be an option for simple case but not really for what we are doing. 
I think that the usability limitation that you are mentioning can be easily overcome in javascript, it should be quite trivial to change the form when the template is changed. Actually this is on our roadmap (but not high priority, this is why it is not done yet). 

Furthermore, we have actually another improvement in our code that allows you to have several  react-jsonschema fields in one form, or several inlined form. This is not really possible with your code because the id of the field is not dynamic. 

We have also other plans for this app, such as providing a route  to serve images saved in base64 in db as if they were files. 

However I do understand that this is not your plan to integrate out changes. We will continue to maintain our fork and make the differences clear in the README. If we start to diverge too much we wlll maybe change the name to be able to publishe the app in Pypi (keeping the credit and license to your work of course).
